name: Build and deploy docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup devenv
        uses: ./.github/actions/setup-devenv
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build docs
        run: |
          devenv shell -- make build-docs
          touch docs/_build/html/.nojekyll

      - uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: docs/_build/html
          single-commit: true
